### ISSUE TITLE
Occasion detail pagina

### ISSUE THREAD

**Issue by IgeBruin** [PizzaSnor/PVB#7]

**Comment by PizzaSnor** [comment]
![Image](https://github.com/PizzaSnor/PVB/assets/70943287/0c4aff76-63d2-4ef0-9a96-49835fca96c6)

Dit is voorlopig hoe de detailpagina eruit gaat zien

**Comment by PizzaSnor** [comment]
## Mobile

![Image](https://github.com/PizzaSnor/PVB/assets/70943287/4aaab715-574c-4a30-b2fd-5e99b5eb5cc2)


![Image](https://github.com/PizzaSnor/PVB/assets/70943287/612e08e0-81e3-431b-8d46-f0eb494228d9)
